add_requires("vulkansdk")
add_requires("libsdl", "vulkan-memory-allocator", "vk-bootstrap v1.3.283", "glm", "fmt", "stb")
add_requires("imgui v1.90.7-docking", {configs = {sdl2 = true, vulkan = true}})
add_rules('utils.glsl2spv', {outputdir = "$(buildir)/$(plat)/$(arch)/$(mode)/shaders"})

target("engine")
    set_kind("static")
    add_files("src/**.cpp")
    add_files("$(projectdir)/shaders/*.comp")
    add_files("$(projectdir)/shaders/*.frag")
    add_files("$(projectdir)/shaders/*.vert")
    add_includedirs("src", { public = true })
    add_includedirs("$(projectdir)/vendor", { public = true })
    add_defines("UNICODE", "_UNICODE", "NOMINMAX", "GLM_FORCE_DEPTH_ZERO_TO_ONE", "GLM_ENABLE_EXPERIMENTAL", { public = true })
    add_packages("vulkan-memory-allocator", "libsdl", "vk-bootstrap", "glm", "fmt", "stb", {public = true})
    add_packages("vulkansdk", {public = true})
    add_packages("imgui", {public = true})
    add_deps("fastgltf", { public = true })
    set_configdir("$(buildir)/$(plat)/$(arch)/$(mode)/assets")
    add_configfiles("$(projectdir)/assets/*.glb", {onlycopy = true})
