add_requires("vulkansdk")
add_requires("libsdl", "vulkan-memory-allocator", "vk-bootstrap", "glm", "fmt", "stb", "imgui v1.90-docking")
add_rules('utils.glsl2spv', {outputdir = "$(buildir)/$(plat)/$(arch)/$(mode)/shaders"})

target("engine")
    set_kind("static")
    add_files("src/**.cpp")
    add_files("$(projectdir)/shaders/*.comp")
    add_files("$(projectdir)/shaders/*.frag")
    add_files("$(projectdir)/shaders/*.vert")
    add_includedirs("src", { public = true })
    add_includedirs("$(projectdir)/vendor", { public = true })
    add_defines("UNICODE", "_UNICODE", "NOMINMAX", "GLM_FORCE_DEPTH_ZERO_TO_ONE", { public = true })
    add_packages("vulkan-memory-allocator", "libsdl", "vk-bootstrap", "glm", "fmt", "stb", {public = true})
    add_packages("vulkansdk", {public = true})
    add_packages("imgui", {public = true})
    add_files("$(projectdir)/vendor/imgui/**.cpp")
    add_includedirs("$(projectdir)/vendor/imgui/backends", { public = true })
    add_deps("fastgltf", { public = true })
    after_build(function (target)
        local build_dir = path.join(target:targetdir(), "assets")
        os.cp("assets", build_dir)
    end)
